### ISSUE TITLE
Sound volume not adjusting when playing/looping sound

### ISSUE THREAD

**Issue by Nordiii** [BlitzKraig/fvtt-SoundBoard#10]
**System:**
FoundryVTT 0.7.5
Current SoundBoard version
dnd5e

**Issue**
Changing the volume bar on the soundboard wont directly change the volume of the playing sound.
~~This also happens when sounds loop, they wont adjust until stopped and started a new~~

**Expected**
Changing the volume is directly reflected with the current playing sound like when you change the volume of a song in the playlist

**Comment by BlitzKraig** [comment]
Hi Nordiii,

Thanks for the detailed reports, I've added both of your issues to my pile. 🙂

**Comment by BlitzKraig** [comment]
Looping sounds should respect the updated volume after completing a loop. I'll need to restructure some of the howler calls to change the audio 'live', but this should be possible.

**Comment by Nordiii** [comment]
Ah yeah you are right, retested and it indeed works as expected when looping.

**Comment by BlitzKraig** [comment]
Added in 1.2.0, releasing soon.

Changing volume now immediately updates the sound. This change is also sent out to players.
Changing the interface volume now updates sounds live too (not sent to players, as the interface volume is a client setting)
