### ISSUE TITLE
Suggestion - Multiple Soundboards

### ISSUE THREAD

**Issue by LadySaga** [BlitzKraig/fvtt-SoundBoard#11]
Yo. Really like this module, and it adds a LOT to the game.

However... I'm one of those who hoard gazillions of sounds, and when I'm building soundboards it get's messy when we suddenly have 1 soundboard with hundreds of folders inside in order to categorize sounds that doesn't want to be wildcard folders.
It would be nice if we could add more than 1 soundboard.
That way we could for instance, have a soundboard for different sources, without needing to:
* Have everything in the same way-too-massive soundboard.
* Manually switch soundboard folder by opening the Module Settings and changing it there.
* Without having to consolidate folders that would be much easier to navigate if they are separated.

For instance, I have a bunch of packs, such as the Syrinscape collection, also a pack with Darkest Dungeons, and from several games and movies, and much more. Some with dialogs, some with sound effects, etc etc etc. All in all, way over 40k files if I do not count music and ambience (since they have a long duration and fit better in the playlist).

So it would be awesome if the SoundBoard interface had a possibility to, basically at the interface instead of the Module Settings, click a Plus or something, that allows us to enter the path to some folder.
That path will turn into a Soundboard, and added as a tab on the top, just like SoundBoard, Favorites and Bundled Audio right now.
And if we click the plus again, we can enter another path, which adds that folder as a tab, without removing the one we just added. :)

THAT would be an AMAZING feature, as we could then also make boards for specific situations and quickly switch between them. :)

**Comment by BlitzKraig** [comment]
Hi, thanks for the suggestion!

I would be interested to hear how well SB works with that many sounds first off. It should automatically collapse all of the categories after a certain number, so as not to destroy Chrome when it tries to render so many buttons at once, but I've not tested with _quite_ that many! Does it all work ok? Does the search functionality work properly with so many sounds?

This suggestion would indeed be useful. I'll have a think at how to implement this, and see if I can add it in the next major version release. Thanks!

**Comment by LadySaga** [comment]
Oh, yeah I don't know how it would handle it, and I can't really try it either, since I'd have to break up my folders a lot, due to the SoundBoard limitation with 1 subfolder _(+1 wildcard folder)_.

Buuuut.. I did try it with the Syrinscape collection a while ago before I broke it up in order to reorganize its folders better (that's currently 20k files), and the module worked without any errors and issues that I could spot. :)
And sure, it slowed down a bit, but not too much, however, even with all folders collapsed there was the issue of scrolling, scrolling, scrolling, scrolling, scrolling... xD

To give a little idea of the folders I have right now, and why it would be a massive boon with multiple soundboards _(or one more level of subfolders... or both boards and subfolders :P)_ I took some screenshots of my current folder structure.
Some of it is sorted and organized, but outside the Unsorted folders I can say that the standalone Neverwinter Nights folder and the Syrinscape folders are also unsorted work in progress stuff. :P
[Behold the folders of an audio hoarder! xD](https://imgur.com/a/3oH0vox)

Yeah, I guess the Forgotten Realms, Warcraft 1-3 and World of Warcraft folders are great examples of trying to sort with 1 subfolder level, using prefixes and so on. :P

...but I forgot to try if the search worked, sooo I'll log in and have a look, then I'll report back on that. :)

_Was going in anyway to take a screenshot of the_ soundboard interface where i could shoddily paint some kind of visual idea of the multiple tabs. :)

**Comment by LadySaga** [comment]
Aight, so I can now say that Search with 9000+ files works, but it's slow. I write what I want to search for, and then it takes a while for it to update. xD which isn't surprising at all thou, but now we can confirm it. More files = longer loading.
Also... scaling the window is super-laggy with 9000+ files. :P

Aaaaand then I added 3 more pictures to that imgur album, but they are about the design and the multi-soundboard stuff, so I'll link them here individually.

**[First one](https://imgur.com/0sE9gaL)** is just a screenshot that shows how big those buttons can be when you have long file names. :P

**[Then I made a quick sketch with the snippet tool](https://imgur.com/yafUYYZ)**. So sorry for the mouse-handwriting. xD
It was a quick "just at the top of my head" thought about those tabs/boards.

**[But then I fired up dev tools, and started fiddling around with the css.](https://imgur.com/7HdFs9N)**
Sure, I won't make stuff actually WORK, but it made it much easier to visualize some thoughts and brainstorm ideas.
I added my thoughts and ideas to the description of the image, but it IS just suggestions. It's your module after all, and the design I made here is just throwing ideas on a wall, seeing what sticks. :D

Let me know what thought you're getting from all this, and if you are wondering anything. I have a tendency to write a wee bit fuzzy sometimes. :P

**Comment by BlitzKraig** [comment]
Hey LadySaga,
Thanks for the further detail!

The first two image links are broken, but your 3rd one works.

I am interested in the idea, I'll just need to work out the logistics. At the moment, the 3 boards are separate apps (which needs improved anyway). I'll spend some time thinking about this, don't expect this feature too soon though unfortunately, as I am very busy with CommunityLighting at the moment.

Thanks!

**Comment by LadySaga** [comment]
Ah, well fortunately they are added into the album so you could just scroll to the bottom. :)

Sounds awesome, and yeah, even if this was your only module (which it isn't), i know that coding and programming is always much more that it looks like, so things take time.
plus, in this case there is also that fact about someone elses idea, then deciding what to do or not do with that idea, plus the other modules, plus real-life stuff, and so on. :P so no worries. :) just knowing that you're considering it is great news! :D
