### ISSUE TITLE
The name parsing is converting weirdly and too much.

### ISSUE THREAD

**Issue by LadySaga** [BlitzKraig/fvtt-SoundBoard#14]
> _"Sound effect names are generated from the file name. CamelCase, underscores and hypens/dashes are all parsed, split and recapitalized to generate the sound name."_

I'm having a problem with this part, as it doesn't work as written.
The reason it doesn't work as intended is because it does more than written.
Plus, there are times when you actually want those DoubleUpperCase letters in a single word, rather than splitting it up, and even more so, are the times when you actually want that dash or hyphen (mostly dashes).

Some examples now when I've been sorting some WoW dialog sounds, we have names like Yogg-Saron, which turns into Yogg Saron, or evertime you're supposed to put two words together with a dash by grammar, but SoundBoard doesn't let us.

But in addition to those issues. It also converts ALL symbols that are not numbers and letters... into numbers and letters.
ALL of them.
It seems like SoundBoard can literally **only** show 0-9 and A-Z, and nothing more, in the file names. And this can make some files -really- weird.
Here are some examples:

**File:** Yogg-Saron (Sara) - [Weak-minded fools!].ogg
> **Result:** Yogg Saron Sara 5 B Weak Minded Fools 5 D

**File:** Yogg-Saron (PuzzleBox) - [effect_04].ogg
> **Result:** Yogg Saron Puzzle Box 5 Beffect 4 5 D

**File:** Echo of Y'Shaarj - [Oh, such... exquisite... pain!].ogg
> **Result:** Echo Of Y 7 Shaarj 5 B Oh C Such

**File:** G'huun - [The contagion... has taken root within you].ogg
> **Result:** G 7 Huun 5 B The Contagion

**File:** G'huun - [Finally... When the planet ruptures like a giant boil, my rot will spread across the cosmos].ogg
> **Result:** G 7 Huun 5 B Finally

**File:** ic_deathwhisper_p2.ogg
> **Result:** Ic Deathwhisper P

**File:** Minsc001.ogg to Minsc0045.ogg
> **Result:** **Minsc 1** to **Minsc 45**)

Due to the deathwhisper p2 to p, I checked Minsc with his 45 files, and yeah, seems like 2 and 0 has some issues as well:
--- | --- | --- | --- | --- | --- | --- | --- | --- | ---
--- | --- | --- | --- | --- | --- | --- | --- | --- | ---
Minsc | 1 |  | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 1
Minsc | 11 | 1 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 
Minsc | 1 |  | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 3
Minsc | 31 | 3 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 4
Minsc | 41 | 4 | 43 | 44 | 45 |  |  |  |  | 

( ) - disappears
the - disappears
, disappears
! disappears
2 disappears _(deathwhisper example)_
0 disappears, but not 4 _(puzzlebox example)_
' is replaced with 7, and adds spaces on both sides.
[ is replaced with 5 B
] is replaced with 5 D
... just cuts it off completely.
_ also disappears, but just as intended, and _ is **rarely** _(if ever)_ used in actual reading names. So that's a good one!

That's the ones I tested so far, mainly because I wasn't deliberately testing them TO test them, but simply noticed that I had a hard time finding, and reading my files, and that's when I noticed.
It's also made even harder due to the fact that, in order to HELP me, I've added the dialog quotes into the filenames, as you can see on the Yogg-Saron and G'huun files, because having Minsc 1, Minsc 2 Minsc 3 etc, yeah I'll never remember what they say (I just haven't fixed that yet as I literally have 5000+ quotes to fix if I do that on all of them. x)

Another issue with this is that it makes them harder to search for, because you might know the filename, but it's broken up by the parsing so you might for instance search for G'huun, and not finding anything.
OR... in the case of ... which just stops the name... well if I search for **planet**, hoping to find _G'huun - [Finally... When the planet ruptures like a giant boil, my rot will spread across the cosmos].ogg_ I simply will not find it, because the name ends after _Finally_ ... and that makes things pretty tricky.

In addition, I thing the flexbox needs to be a bit tweaked with the width and height so it doesn't build super-tall pillars on long sentences, but tries making longer ones instead to make things easier.
I did find a perfect way to fix that when I fiddled around yesterday, but ofc forgot to save that, and today when I was going to do some style changes with the Stylus extension I couldn't find it again... x) but at least I managed to shrink the font-size for me personally. XD (that's not something that needs to be done thou, the font-size is a me-thing, as I have... long quoted filenames. XD)
[But eh, here is a picture showing what I mean. :)](https://imgur.com/DOE1cy1)

**Comment by LadySaga** [comment]
Heyo! I know you've been busy with life and all, just wanted to check in if there is any update on the progress on this? :)

I'll attach a screenshot here which shows how weird it can get when you have dialog soundfiles for instance, where I marked one of the sounds to make it even more clear how it's a bit... hard to read. :)
The narrow width of the buttons also make it pretty tricky to read.

![soundboard](https://user-images.githubusercontent.com/37087535/109578742-063bea00-7af8-11eb-9a00-d54786c22594.JPG)

_(Sidenote, I've used Stylus css for the other tweaks like font size and stuff, just incase you wonder why it looks a bit different ^^)_

**Comment by BlitzKraig** [comment]
Hi,
Thanks for the feedback
I'm carving out some time at the moment to update all of my modules, apply fixes and make some minor improvements.
I've just completed EasyTable, and SoundBoard is next on the list, so I sould get round to looking at this soon.

Thanks for the extra info, that should help. This should be a relatively simple fix, as far as I can tell, and quite an important one, so I'll prioritise it for the first pass of the update.

Thanks again

**Comment by LadySaga** [comment]
Oh, awesome to hear!
Guess I need to start working on sorting out my files then with which goes where and which ones goes into the wildcard folders. ^^

_Also hoping for that multiple soundboards thing I think i posted in another post, but without any coding expertise it still sounds like a much tricker fix that this parsing thing. :P so no stress! :)_

**Comment by BlitzKraig** [comment]
Fixed in 1.2.0, releasing soon.

Note that `-` and `_` will be replaced with spaces, unless spaces already exist on both sides of the character

`foo-bar.ogg` will render as "Foo Bar"
`foo - bar.ogg` will render as "Foo - Bar"
