### ISSUE TITLE
Feature Suggestion - Voice Chat Selective Player Mute

### ISSUE THREAD

**Issue by Dick-K** [BlitzKraig/fvtt-SoundBoard#15]
Roll20 has a feature on their native voice chat where a GM can voice chat whisper to a single player. This prevents all other players from hearing the GM until the GM toggles the switch.
Any possibility this could be rolled into Sound Board (great module, btw!) so that a Foundry GM could do this? I have raised a core feature request but just wondered whether this might be easily done in SB.

All the best and thanks for the great work.

**Comment by BlitzKraig** [comment]
Discussed on Discord. This is a fantastic idea, and I hope somebody makes it, but well outwith the scope of SoundBoard, and would require a very different approach than targetted sounds in SB.

Thanks for the feedback!
