### ISSUE TITLE
make wildcard folders from some module sounds

### ISSUE THREAD

**Issue by odulac** [BlitzKraig/fvtt-SoundBoard#16]
for exemple: the "hideous laughter" by Rive: most of those soundbites are in fact short & repeated variations of something (ex: Demon laugh= several different laughs separated with a very short delay): it would be cool if those were **wildcard sounds** (ie, the file separated in each of those variations, and put in a subfolder) instead (making them less repetitive when used in repetition)

**Comment by BlitzKraig** [comment]
I misread this ticket initially;
I have made some improvements to the bundled audio regarding wildcards - made some wildcards that should have been, and removed some that ended up with only one sound.

However, the Hideous Laughter pack is working as intended. The Demon Laugh for example has _very_ short gaps, and is one continuous laugh. It was designed to be used after Hideous Laughter (5e) was cast on a creature as far as I'm aware.

If you want shorter wild-card versions, you could always cut the clips yourself and create a wildcard directory in your user soundboard.

Thanks for the feedback!
