### ISSUE TITLE
Faster alternatives to the ... submenus

### ISSUE THREAD

**Issue by odulac** [BlitzKraig/fvtt-SoundBoard#18]
During play, clicking the "..." submenu and choosing the appropriate playing strategy (loop, one time, etc) is quite slow. It would be nice to either have:
  - a different click action with modifiers (ex: alt+click to "loop" the sound clicked, shift+click to "stop after current play", etc)
  - and/or also: have the "loop"  "stop after 1 play" etc directly available within the button itself (for exemple by dividing the button into different regions... left-side for regular play, right-side for "stop this sound", middle for loop-play? but it may be difficult to clearly indicate that, and may end up unreadable or inconvenient. Maybe as an option?)

**Comment by BlitzKraig** [comment]
For release 1.2.0:

Shift-click to begin looping
Alt click to favourite/unfavourite
Ctrl-click to stop sound
