### ISSUE TITLE
Shortcut or Macro to Open SoundBoard

### ISSUE THREAD

**Issue by brunocalado** [BlitzKraig/fvtt-SoundBoard#2]
Hi. First, you did an amazing job. This is the best sound module for foundry. 

Is it possible to add a shortcut or a macro to open the SoundBoard without have to go to playlist?

Thank you.

**Comment by BlitzKraig** [comment]
Hey, thank you!

There are currently buttons in the Audio tools on the left as well.

Alternatively, if you want to set up a macro, it should work by just using `SoundBoard.openSoundBoard()` in the macro.

You can also use `SoundBoard.openSoundBoardBundled()` and `SoundBoard.openSoundBoardFav()` to open your bundled or favorited board instead.

Hope that helps!
