### ISSUE TITLE
Suggestion : stop sound one by one

### ISSUE THREAD

**Issue by Darshyne** [BlitzKraig/fvtt-SoundBoard#22]
Hello, would it be possible to stop one sound at a time and not all? Maybe clicking on a sound twice can stop it instead of playing it again.
Thank you for this great mod

**Comment by jenthura** [comment]
I second this!

**Comment by simulacrum-1** [comment]
I agree. Would be great. Especially with a fade out.

**Comment by BlitzKraig** [comment]
Will release in 1.2.0, see #18
