### ISSUE TITLE
Add the ability to link sounds in journals

### ISSUE THREAD

**Issue by Puddinglord** [BlitzKraig/fvtt-SoundBoard#25]
The soundboard window itself is great when you need sounds on the fly.

Most of the time I have everything prepped in journals and I have to read and click on the soundboard at the same time. It would be wonderful if I could link a sound, not unlike linking an item from a compendium to a journal entry so that when I click the linked text, it plays the linked sound.

For example:
*The door `creaks (linked to creaking door)` open revealing a grimy room festooned with debris. As you enter, a fat rat knocks over a stack of old plates that `break (pottery smash)` as they come crashing to the floor.*

Thanks for a wonderful module!

**Comment by BlitzKraig** [comment]
Hi, thanks for the feedback.

I agree that this would be useful, though not sure how tricky it would be to implement given the way I've set up the module base.

I'll have a think about it and keep this ticket open,
thanks

**Comment by BlitzKraig** [comment]
I've come up with a solution for this that will be releasing in 1.2.1

Thanks for the feedback!
