### ISSUE TITLE
Wrong Sound Effect - Tavern Chair

### ISSUE THREAD

**Issue by illcom94** [BlitzKraig/fvtt-SoundBoard#27]
Just installed this, and the sound effect that is labeled as a chair under tavern is a truck horn.

**Comment by BlitzKraig** [comment]
Hi, thanks for the feedback

That sound is from the 'example' soundset, designed to show you how your custom directory should be set up.

It is, in fact, a chair being moved, though I can understand the confusion; it does sound a bit like a horn.

Thanks
