### ISSUE TITLE
Search Improvement

### ISSUE THREAD

**Issue by brunocalado** [BlitzKraig/fvtt-SoundBoard#3]
Hi!

Is it possible to make search be able to search the musics or the tille of the folders?

Ex.: I want battle sounds. But, the musics don't have **battle** in the name. They're in a folder with the name **Battle Musics**.

Thank you.

**Comment by BlitzKraig** [comment]
Hi Bruno.

This should be possible, yeah, I just didn't include it as I wasn't sure it was the best way to filter.

I can look at adding it as an option you can enable in settings; "Filter on Category Name"

**Comment by BlitzKraig** [comment]
Hi Bruno,

This one is going to be a bit tougher than I originally thought, but should still be possible.
It's fairly low on my priority list, but I'll try to get to it.

Thanks

**Comment by BlitzKraig** [comment]
Hi Bruno,

After some review, I've decided against adding this functionality, as it causes more potential problems than it solves.

Note that you can Collapse All categories to easily find your required "Battle" category, then click it to expand just that category.

Apologies for the delay, I've been very busy.
