### ISSUE TITLE
Sound not being heard by other players

### ISSUE THREAD

**Issue by cody-norman** [BlitzKraig/fvtt-SoundBoard#30]
doesn't matter if a gm on the program or a player on web selects a sound no one but the person who clicked the button can hear it.

**Comment by BlitzKraig** [comment]
Hi cody,

Are you left clicking? Have your players made sure their Interface/Soundboard volume in the playlists directory is not muted?

**Comment by cody-norman** [comment]
![image](https://user-images.githubusercontent.com/59719778/107699288-1be58e80-6c73-11eb-930b-a8fe9250d499.png)
Yes both sides have the soundboard volume up and we are left clicking but this screenshot shows that only "everyone" is able to be selected but on the bottom left im showing that two of use are connected

**Comment by BlitzKraig** [comment]
Hmm, that's interesting.
It looks like SoundBoard straight up can't see the player.

I'll take a look at this and see if I can reproduce.

How are you hosting the server? What browsers do you and this player use?

**Comment by cody-norman** [comment]
I am hosting via ip although there are two links they can join by, one is regular internet ip and the other is hamachi, both links have this issue. they are using Chrome. Im using the windows program (not sure if you can host on browser but i figured i would say anways)

**Comment by BlitzKraig** [comment]
Excellent, thanks for providing the details, should help with debugging

**Comment by cody-norman** [comment]
in case its worth some insight. We can use the built in playlist system no problem.
