### ISSUE TITLE
Additional Worlds no Sound

### ISSUE THREAD

**Issue by cyberpatriot000** [BlitzKraig/fvtt-SoundBoard#31]
Other than my first world, no sound ever plays.  Every world, minus the first, gives a JS error listed below.

foundry.js:5956 Foundry VTT | Retrieved and compiled template modules/SoundBoard/templates/soundboard.html
foundry.js:4503 Foundry VTT | Rendering SoundBoardFavApplication
foundry.js:4503 Foundry VTT | Rendering SoundBoardBundledApplication
soundboardaudiohelper.js:33 Uncaught (in promise) TypeError: Cannot read property 'createGain' of null
    at SBAudioHelper.play (soundboardaudiohelper.js:33)
    at Function.playSound (soundboard.js:114)
    at Function.playSoundOrStopLoop (soundboard.js:89)
    at HTMLButtonElement.onclick (game:1)
play @ soundboardaudiohelper.js:33
playSound @ soundboard.js:114
playSoundOrStopLoop @ soundboard.js:89
onclick @ game:1

**Comment by BlitzKraig** [comment]
Thanks for the report, I'll take a look at this

**Comment by BlitzKraig** [comment]
This looks like it may be linked to #23 and #8 

These issues have been fixed in 1.2.0, which will release soon.

If you are still having issues when 1.2.0 releases, please feel free to re-open a ticket.

Thanks for the feedback!
