### ISSUE TITLE
HTTP error: status code 404 for SoundBoard/dependencies/bootstrap.bundle.min.js.map:

### ISSUE THREAD

**Issue by UrielMhezzek** [BlitzKraig/fvtt-SoundBoard#32]
I get a warning at starting Foundry
DevTools failed to load SourceMap: Could not load content for [myurl]/modules/SoundBoard/dependencies/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

At my filesystem i found a "bootstrap.bundle.min.js" file. the following postfix .map is missing, or not?

**Comment by BlitzKraig** [comment]
Hi,
The mapping file is not present. This is intentional, and the warning is only triggered if devtools is opened.

Thanks
