### ISSUE TITLE
Suggestion: Make sounds draggable to hotbar

### ISSUE THREAD

**Issue by Nedrapter** [BlitzKraig/fvtt-SoundBoard#38]
When you have large collection and only few sound are relevant for your session, having them in your hotbar instead of looking for them is very useful. Please make them able to be dragged into the hotbar.

**Comment by BlitzKraig** [comment]
Hi,

Using Macro-mode in 1.3.0, you can generate a macro that you can put in your hotbar.

See the help section (top right of your soundboard) for more info

**Comment by Nedrapter** [comment]
> Hi,
> 
> Using Macro-mode in 1.3.0, you can generate a macro that you can put in your hotbar.
> 
> See the help section (top right of your soundboard) for more info.
> 
> Also keep in mind you can link the sounds in a journal, which may suit your needs better.

Thanks! I was still in 1.2.0 and wasn't aware of it!

**Comment by BlitzKraig** [comment]
The saved macro will appear in your macro directory (folder button to the left of your hotbar)

If you have a journal currently being editted, the macro will be linked in the journal at the last editted location.

**Comment by Nedrapter** [comment]
Thank again, I never actually seen that folder icon ! I was looking at compendium macros!
