### ISSUE TITLE
Error on Boot

### ISSUE THREAD

**Issue by Motara7** [BlitzKraig/fvtt-SoundBoard#39]
First off, thank you for this module. It's perfect for the kind of game I like to run.

I am getting this error (caution) when Foundry loads:

Cannot GET /modules/SoundBoard/dependencies/bootstrap.bundle.min.js.map

It doesn't seem to prevent the module from working. I'm just trying to clean up the numerous cautions/errors I'm getting at startup. So, I figured I'd check with you to see if this is something I need to worry about.

Thanks again!

**Comment by BlitzKraig** [comment]
Hi Motara7,
The warning is ignorable - I have not provided the mapping file for the customised bootstrap.
This warning is only generated when DevTools is opened, so it will not cause any issues or slowdowns.

Thanks for the feedback!
