### ISSUE TITLE
I can't Reopen SoundBoard after Close it

### ISSUE THREAD

**Issue by brunocalado** [BlitzKraig/fvtt-SoundBoard#4]
Hi!

I can open SoundBoard, but after close it, I can't reopen. The console shows an error. This error happens after press the button **Open SoundBoard**.
![image](https://user-images.githubusercontent.com/4999783/95020778-94906a80-0643-11eb-85a3-618db8097e36.png)

**System**
![image](https://user-images.githubusercontent.com/4999783/95020755-6ca10700-0643-11eb-8d58-9c3993ef28c4.png)

**Music Folder**
![image](https://user-images.githubusercontent.com/4999783/95020801-b8ec4700-0643-11eb-83c7-849efbb2fa46.png)

**Comment by BlitzKraig** [comment]
Hi,
Do any of your soundfiles have accented characters in them?
The regex I use does not handle these well at the moment, I'll need to add an update to support them.

I'll add a check in at this stage of the formatName function at least, which should prevent a fatal error. I will look into it this week.

Thanks

**Comment by brunocalado** [comment]
> Hi,
> Do any of your soundfiles have accented characters in them?
> The regex I use does not handle these well at the moment, I'll need to add an update to support them.
> 
> I'll add a check in at this stage of the formatName function at least, which should prevent a fatal error. I will look into it this week.
> 
> Thanks

I couldn't find accented characters. But, there is a lot of special characters (! [] & () )

**Examples**
![image](https://user-images.githubusercontent.com/4999783/95022138-b130a080-064b-11eb-9427-3c1e99e1355e.png)

Big Action 2 - !BONUS! Action Powerful Energy Loops

Loops Mini Set Casual & Abstract Game Loops

Lyric Voices - Choir Music Pack [wav]

**Comment by BlitzKraig** [comment]
Thanks for providing that, I'll run some tests based on this and see if I can break it

**Comment by BlitzKraig** [comment]
Hi Bruno, please give 1.1.5 a try.

I was unable to pinpoint exactly what causes the error, but my changes should prevent it from actually breaking.

If it works, please check for any soundboard buttons with unformatted names, and send me the details - these should be the filenames with the incompatible characters, which I can then add support for fully.

Thanks!

**Comment by brunocalado** [comment]
Hi.

Nice work. Thank you.

I can reopen soundboard now.
