### ISSUE TITLE
Can't stop individual tracks.

### ISSUE THREAD

**Issue by CanDincer** [BlitzKraig/fvtt-SoundBoard#41]
There is only an option to stop all tracks. Because I want to change the music while leaving ambiance sound effects playing, I can't use this module.

**Comment by BlitzKraig** [comment]
Hi Can,
I wouldn't recommend playing your music via SoundBoard, that's probably best left for Playlists, but it is possible.

Anyway, hold CTRL and click a sound to immediately stop it - the hotkeys are all explained in the Help section at the top right of the soundboard.

Thanks.
