### ISSUE TITLE
Volume for every sound

### ISSUE THREAD

**Issue by smoothingplane** [BlitzKraig/fvtt-SoundBoard#43]
could you insert a button in the overlay that allows you to adjust the volume of the clip?

**Comment by BlitzKraig** [comment]
Hi,
This is something I've been looking to add for a while, but haven't found the right way to do it yet without dirtying the UI.
I'll take another run at it soon.

**Comment by qwoodmansee** [comment]
#46 I opened a draft PR for this. Hopefully Blitz gets eyes on it and can help the 1-2 missing pieces

**Comment by BlitzKraig** [comment]
Implemented in 1.5.1, based on #46 with some changes.

Thanks, will release soon
