### ISSUE TITLE
Sounds not playing in Foundry 0.8.3

### ISSUE THREAD

**Issue by kamcknig** [BlitzKraig/fvtt-SoundBoard#45]
Sounds don't seem to play in Foundry 0.8.3 though the project page says it's compatible with 0.8.1+

Getting the following console error in Chrome

![2021-05-17 12_13_44-Window](https://user-images.githubusercontent.com/705490/118522091-af62ab80-b709-11eb-8d08-09016b97a313.png)

**Comment by BlitzKraig** [comment]
Fix awaiting releaseOn 17 May 2021 17:16, Kyle McKnight ***@***.***> wrote:
Sounds don't seem to play in Foundry 0.8.3 though the project page says it's compatible with 0.8.1+
Getting the following console error in Chrome

**Comment by BlitzKraig** [comment]
Hi,
The fix for 0.8.3 is in the next release candidate branch, and will be released once I've cleared the other tickets I want in that version.

Thanks
