### ISSUE TITLE
Buttons Visibility

### ISSUE THREAD

**Issue by brunocalado** [BlitzKraig/fvtt-SoundBoard#5]
Hi.

Is it possible to make these buttons a little more visible? Maybe red for the stop.
![image](https://user-images.githubusercontent.com/4999783/95662627-a4f68880-0b0e-11eb-8101-39a4930ba083.png)

Thank you.

**Comment by BlitzKraig** [comment]
Hi,I think you have another UI theme active? That doesn't look like the normal soundboard colours.SB also supports whetstone, if you want to customise the colours furtherOn 10 Oct 2020 19:40, Bruno Calado <notifications@github.com> wrote:
Hi.
Is it possible to make these buttons a little more visible? Maybe red for the stop.

Thank you.

**Comment by brunocalado** [comment]
Just soundboard. Maybe is the DW System then.
![image](https://user-images.githubusercontent.com/4999783/95662903-be98cf80-0b10-11eb-9d17-fc6fc95b7471.png)

**Comment by BlitzKraig** [comment]
Thanks for the feedback. I'll take a look at Dungeon World and see if there's an easy way to enforce proper themeing.

Cheers

**Comment by BlitzKraig** [comment]
Hi,
I've had a look at DungeonWorld. Unfortunately, DW applies blanket rukes to a bunch of elements.

SoundBoard only applies its rules to children of #soundboard-app, and anything that's inherited from bootstrap is overridden by DW css. I could specify each 'broken' element and manually theme it, but that's going to cause further problems for other systems.

You can use the custom CSS module to fix this, or contact the Dungeon World developer.

Thanks

**Comment by BlitzKraig** [comment]
Re-opening with workaround

**Comment by BlitzKraig** [comment]
Closing as fixed in 1.2.0
