### ISSUE TITLE
Allow multiple source directories/buckets

### ISSUE THREAD

**Issue by ctbritt** [BlitzKraig/fvtt-SoundBoard#51]
May be a dumb question, but how do I set the soundboard directory on s3 when I have more than one bucket?

**Comment by BlitzKraig** [comment]
Hey ctbritt,
As far as I understand it, you can't at the moment. You may be able to make it work server-side if you know what you're doing, but that's a little out of my wheelhouse.

I'll convert this ticket to an enhancement to allow multiple source directories/buckets though, as it would be a useful feature

Thanks
