### ISSUE TITLE
Some Sounds Not Playing

### ISSUE THREAD

**Issue by JBlocklove** [BlitzKraig/fvtt-SoundBoard#55]
So far I'm loving using this, but it appears that some of my custom tracks just won't play. They're all MP3 format and many of the other tracks in the folders work just fine, so I'm not sure what's going on. I assume it's an issue with the tracks themselves, but I can't for the life of me figure out what's wrong with them. Any ideas?

Also, is there a debug mode or a log of some kind that I can look at to try to diagnose if the soundboard is throwing an error or something with those tracks?

**Comment by BlitzKraig** [comment]
Hi,
Could you DM me on Discord and share one of the sounds you're having a problem with?
I can try it on my build and see if I can spot anything

Thanks

**Comment by BlitzKraig** [comment]
Hi @JBlocklove ,
I've tested with the track you sent, and seeing it work fine for me.
Are you running the latest Foundry and SoundBoard?
Do you see any errors in the console when you attempt to play one of the broken files?
