### ISSUE TITLE
Allow S3 bucket selection

### ISSUE THREAD

**Issue by elena-v2** [BlitzKraig/fvtt-SoundBoard#56]
Currently, SoundBoard always uses the first bucket, which is usually whatever is alphabetically first. If you have multiple buckets, this is quite limiting.

You can see the relevant line for the current behavior here https://github.com/BlitzKraig/fvtt-SoundBoard/blob/bb0675b85ee9e388c701b63447d441202e7a794a/soundboard.js#L562

Allowing you to specify a bucket from a drop-down list of all available buckets would be far more useful, and would be a comparatively simple change.

**Comment by BlitzKraig** [comment]
Hi elena,
I don't personally use S3 buckets, most of the functionality was provided by another dev iirc.
If you think you know how to handle this, please feel free to create a PR and I'll try to get it merged in asap.

Thanks
