### ISSUE TITLE
System TDE/DSA 5: UI is not really compatible to the System

### ISSUE THREAD

**Issue by vt-tom** [BlitzKraig/fvtt-SoundBoard#58]
The UI of the Soundboard is not compatible with the System The Dark Eye/Das schwarze Auge 5. Some elements get stuck in the top while scoling down. 
It would be very helpful if you can fix this.

Example: 
![grafik](https://user-images.githubusercontent.com/80099175/134633114-9455a269-e236-41cb-bb60-3388cc5490a9.png)

**Comment by Xermen** [comment]
Are there any updates to solve the problem?
