### ISSUE TITLE
Sound fade in and fade out

### ISSUE THREAD

**Issue by MorganVergara** [BlitzKraig/fvtt-SoundBoard#59]
Is there a way to have the sound fade in instead of just playing at full volume and fade out when stopped instead of just stopping?

**Comment by BlitzKraig** [comment]
Hey,
That's not something I'm interested in adding, I normally use SoundBoard for short one-shot sounds that wouldn't require fading.
If you want to create a PR to make it an option, I'd gladly review and merge.

Thanks
