### ISSUE TITLE
Macro for opening soundboard

### ISSUE THREAD

**Issue by jacksands** [BlitzKraig/fvtt-SoundBoard#60]
There is a macro for quick opening soundboard?
If colapse all option enable even better!

Thanks!

**Comment by BlitzKraig** [comment]
You can use
`SoundBoard.openSoundBoard()` to open the board, or `SoundBoard.openSoundBoardBundled()`, `SoundBoard.openSoundBoardFav()`

When it's open, you can use `SoundBoard.openedBoard.close()`, `SoundBoard.openedBoard.minimize()` and `SoundBoard.openedBoard.maximize()`
