### ISSUE TITLE
Suggestion - Option to Pad Loop with Empty Space

### ISSUE THREAD

**Issue by mcbobbo** [BlitzKraig/fvtt-SoundBoard#69]
Rather than have a sound repeat immediately, would be nice to intermittently have a pause in between.  Instead of "sound > sound > sound > sound", more of a "sound > ....pause.... > sound > ....pause.... > sound"

**Comment by BlitzKraig** [comment]
This is already possible, click the 3 dots on a sound button and select a delay duration
