### ISSUE TITLE
New Soundboard folder

### ISSUE THREAD

**Issue by thesnoman** [BlitzKraig/fvtt-SoundBoard#71]
I keep getting an error message after I created the new soundboard folders (moving from exampleAudio).  I created them both outside and inside the Soundboard folder.  I got the error message in both cases.  I tried pointing back to the exampleAudio folder, but continue to get the error message.   I uninstalled the module and reinstalled it and still the same issue.  I'm sure that I'm doing something wrong.  Any help would be much appreciated!
Thanks
JPS

**Comment by pandakat** [comment]
I'm having the same issue. I made a sound folder in my foundry Data folder with one sub folder for each "type" of sound. used the built in file picker and tried copy/pasting the file location neither one worked
