### ISSUE TITLE
Sounds sometimes won't stop when I click Stop 

### ISSUE THREAD

**Issue by victor-am** [BlitzKraig/fvtt-SoundBoard#80]
Sounds sometimes won't stop when I click Stop and also this error shows up after the sounds finish playing:

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/13217785/196469384-fbee5173-599a-4e6c-b876-376691df2286.png">

**Comment by DrKenReid** [comment]
I am having the same issue.

**Comment by DrKenReid** [comment]
Would this solve it? Modify SoundBoard.audioHelper.stopAll() method:

```
stopAll() {
  for (let sound of this.activeSounds) {
    // Disconnect the AudioNode from its destination
    // before attempting to stop it
    if (sound.context.destination) {
      sound.disconnect(sound.context.destination);
    }

    try {
      sound.stop();
    } catch(e) {
      // Do nothing
    }
  }
  this.activeSounds = [];
}

```

**Comment by Tupsi** [comment]
same problem here. I would remove the "sometimes" from the issue though in my case. The stop button just does nothing here atm.

**Comment by BlitzKraig** [comment]
When using SoundBoard on ForgeVTT, the sound does not stop the first time you play it.
After it has been played once, the sound will stop on subsequent plays.
Investigating.

**Comment by BlitzKraig** [comment]
In Foundry, long-duration sounds or streaming audio (such as via forge before caching) use `MediaElementAudioSourceNode` instead of `AudioBufferSourceNode`.
This causes a few problems with the detuner, and when attempting to stop sounds.

The audio element is now paused and removed for these sounds, which should fix the issue.
